### PR TITLE
updating home button functionality

### PR DESCRIPTION
**Pull request by DylanGlynn**

### CODE REVIEW

**Review by Adajolson — APPROVED** [review]
Looks good!

**Review by amathews043 — CHANGES_REQUESTED** [review]
in PostList line 21 needs to be let favorites (instead of const). Also we need to keep lines 36-45 in order for the filter favorites function to work

**Review by amathews043 — APPROVED** [review]

**Review by Adajolson — APPROVED** [review]
looks good to me

**Comment by amathews043** [comment]
nice work!

**Pull request merged**
